### ISSUE TITLE
Global GUI facelift

### ISSUE THREAD

**Issue by cknaut** [lukingroup/pylabnet#134]
Match all css attributes to new template stylesheet. We will be transitioning to this style:
![image](https://user-images.githubusercontent.com/4958226/94939008-8d305c00-049f-11eb-82c3-4b1c52ee5f5b.png)

https://github.com/ColinDuquesnoy/QDarkStyleSheet

We will need to add some custom colors for red / green buttons, and make sure all style attributes are defined in a global .css style-sheet, and not as attributes in the `.ui` files.

**Comment by mkbhaskar** [comment]
now done with `qdarkstyle` in almost all GUIs including launcher (to be added, see b16-fibercoupling branch)
