### ISSUE TITLE
Move config files outside repository

### ISSUE THREAD

**Issue by cknaut** [lukingroup/pylabnet#147]
Config files should be specified outside of the repository (e.g. in experimental data directories), but should still be conveniently accessible without having to repeatedly specify complicated filepaths

**Comment by mkbhaskar** [comment]
An alternate strategy might be to allow the config files to be easily modifiable through the package itself, e.g. to create a program/GUI that allows the user to edit the config files without having to do so directly through the filesystem. This would be compatibile with e.g. pip deployment of the software
