### ISSUE TITLE
Distinct Devices Sharing Same Device ID Conflict

### ISSUE THREAD

**Issue by danielra97** [lukingroup/pylabnet#174]
Currently multiple different devices of the same hardware class with different config files can have the same device_id, leading to issues where pylabnet does not know which device to provide the scripts (since internally it looks up instantiated device servers via their device_id), thereby requiring user input to solve the problem. For example, we have multiple DAQs with device_id CDaqMod1 (green DAQ and TiSaph DAQ), leading to conflicts.

Solution should likely be that the name of the config file is appended to the server name as opposed to the device_id. In addition, lookup of servers should be via the config file name as opposed to the device_id, so device_id is only known and used internally by the given hardware device driver.

**Comment by cknaut** [comment]
![image](https://user-images.githubusercontent.com/4958226/104507135-53014b00-55b4-11eb-831d-cbcef8d688a7.png)

**Comment by mkbhaskar** [comment]
The device id's can also be changed via NI MAX. I would recommend doing this for a device not in use in B16 by labview software, so that our devices have unique IDs.

But in general, I support moving to config based identification.
