### ISSUE TITLE
Find solution to hard-shut-down dangling servers on master launcher

### ISSUE THREAD

**Issue by cknaut** [lukingroup/pylabnet#200]
Using the staticproxy implementation, it is now impossible to remove references to dangling servers in the launcher list (since a restart of the launcher is jeopardizing other experiments). We'd need to find a way to remove dangling servers gracefully from the master logger to avoid multiple servers listed per hardware device.

**Comment by mkbhaskar** [comment]
@cknaut can you elaborate on this? I am able to use the `Close server` button in the current branch of master to close any unwanted servers, both from the `master` and from the `staticproxy` control windows

Are you referring to `LogClients` that don't have their own server running, due to some sort of bug or failure?

**Comment by cknaut** [comment]
Yes, exactly, I mean the later case where `LogClients` are dangling due to bugs.

**Comment by mkbhaskar** [comment]
Ok in that case i understand and fully agree, i can try and look into it over the weekend.

**Comment by mkbhaskar** [comment]
Reopening as this does not work when operating with the `staticproxy`, likely due to following lines of code in `pylabnet.launchers.launch_control.Controller._close_dangling` method:
```python
del self.port_list[client_to_stop]
del self.client_list[client_to_stop]
del self.log_service.client_data[client_to_stop]
del self.client_data[client_to_stop]
```

**Comment by pieterjanstas** [comment]
Issue has been solved. Dangling servers can now be successfully shut off, after which new servers can be launched without a problem.
