### ISSUE TITLE
Compilation of pulseblocks into CSV without AWG modulation in Pulsemaster

### ISSUE THREAD

**Issue by huanyanqi** [lukingroup/pylabnet#211]
- Currently when we add a modulated Gaussian, we specify the pulse width/time and modulation frequency, and the envelope is compiled into a CSV while the modulation is done by the AWG
- Want to add option to compile the waveform CSV for a particular pulseblock (or a particular channel in the pulseblock) using direct waveform synthesis, i.e. include the actual modulation in the compiled waveform
  - Will be useful for complicated pulse sequences (e.g. XY8) that require multiple frequency changes played one after another
  - Will be used for RF pulses

**Comment by cknaut** [comment]
@huanyanqi , is this still current?

**Comment by huanyanqi** [comment]
It may be useful depending on how the AWG channels are configured. Possible use case:
- When you need to do X and Y pulses on RF with precise timing gaps between them, but do not have the MF mod / are unable to spare 2 channels for the 0 and 90 degree phase modulation waveforms. In this case, you would need directly synthesize the RF waveform with the 2 phases instead of relying on the in-built modulation since the command to switch phases on the fly takes time.

If a scenario like this does not apply, then this function will not be useful.
