### ISSUE TITLE
Add email notification add-on for datataker

### ISSUE THREAD

**Issue by cknaut** [lukingroup/pylabnet#215]
Should be able to send out notifications based on current measurement values and flexibly defined thresholds. The idea is to for instance get an email when we decoupled, or get an hourly status update email about key metrics of the experiment.

**Comment by mkbhaskar** [comment]
Even better might be to create a slackbot for our experiments, to prevent email churn. We did this even in labview to notify when our lasers came unlocked (although we never implemented it too effectively)

https://www.fullstackpython.com/blog/build-first-slack-bot-python.html

**Comment by cknaut** [comment]
Integrated slackbot to logger: #224
