### ISSUE TITLE
Staticline Loading without Connected Device Servers

### ISSUE THREAD

**Issue by danielra97** [lukingroup/pylabnet#238]
Currently the staticline GUI won't load if it is unable to connect to any of the device servers it wants to connect to. It would be cleaner if the staticline GUI would still load and just would remove entries related to whatever device server it could not access.

**Comment by cknaut** [comment]
Ideally, this should be solved globally by allowing all scripts that depend on servers to launch, then perform a connection check for all required servers, show disconnected servers as greyed out, and provide meaningful error messages when experiments which depend on disconnected servers are launched.
