### ISSUE TITLE
Re-implement server-list communication

### ISSUE THREAD

**Issue by cknaut** [lukingroup/pylabnet#307]
Currently, the list of open servers is communicated to a remote instance of the launch control by passing the list as command-line arguments. This imposes a maximal number of servers that can be open at the same time, which is not a scalable solution. This implementation should be redone in a way that is agnostic to the absolute number of servers passed.

One potential implementation is to add some sort of networking layer which allows for the interchange of launcher-related information. This could potentially be implemented by `rpyc` itself.

**Comment by huanyanqi** [comment]
@cknaut Should this be closed after the PR for #304 ?
