### ISSUE TITLE
Investigate B16 server random crashes (count monitor, wavelength monitor)

### ISSUE THREAD

**Issue by huanyanqi** [lukingroup/pylabnet#308]
Possibly related to #306 

However, that issue appears to occur when interfaced with Python, while we also get random crashes for no apparent reason. This either causes only those servers to crash or it can cause the entire local Pylabnet to crash and requires a restart.

![image](https://user-images.githubusercontent.com/36173574/150857475-2932ddb7-1933-40e7-a863-29697b6ab4e4.png)
![image](https://user-images.githubusercontent.com/36173574/150857494-d26f5e4e-e6e3-4c89-9a6c-f9f54f3a1e24.png)

**Comment by cknaut** [comment]
Reason to believe this is Goldberry-specific. Since Goldberry has been replaced, let's see if it still is an issue.

**Comment by pieterjanstas** [comment]
Problem has stopped appearing once we switched out Goldberry.
