### ISSUE TITLE
Connection to QM device

### ISSUE THREAD

**Issue by mkbhaskar** [lukingroup/pylabnet#320]
Create driver for connecting to QM device using pylabnet

**Comment by mkbhaskar** [comment]
Thanks @YanChengWeiTony. I will start to have a look at the files you mentioned and add them to the repository.

**Comment by YanChengWeiTony** [comment]
@mkbhaskar Added relevant notebooks on the "qm_testing" branch
will write a driver later

**Comment by YanChengWeiTony** [comment]
@mkbhaskar, just wrote a raw-version driver and a demo file, please check the git's "qm_testing" branch

**Comment by mkbhaskar** [comment]
@YanChengWeiTony - looks good! Made a few minor changes for code hygiene and tested the connection, execution, and simulation from Dolores. Feel free to have a look, but I am marking this closed.
