### ISSUE TITLE
Staticline -DIO wrong analogue setting

### ISSUE THREAD

**Issue by YanChengWeiTony** [lukingroup/pylabnet#350]
To access B16's DIO from G12's computer (Roger) or vice versa (from Caleb), it should be solved simply by having configure files. But even with that, the analogue voltage setting is not set correctly by staticline. Specifically, when using Roger to access B16's DIO and setting Certain DIO's analogue's voltage to some value, the corresponding DIO's voltage does not change. 

The reason being the DIO's  connection is different between two labs, and it requires "awg_dio_pin_mapping.json" for calling the staticline in the very beginning. It cannot be changed in a flexible way now.

![image](https://user-images.githubusercontent.com/26712226/199777180-11ed5e10-4650-4287-b462-d1fbb30b09bd.png)

**Comment by huanyanqi** [comment]
Also the previous code was hardcoded to only have boards 0-1 and 2-3 and nothing else, but now B16 has multiple breakout boxes so we need to have multiple copies of the same board numbers that cover different channel ranges.

See branch "DIO_mapping_assignment"
