### ISSUE TITLE
Code driver for MCC USB-1608GX DAQ

### ISSUE THREAD

**Issue by pieterjanstas** [lukingroup/pylabnet#402]
https://digilent.com/reference/software/python-support-for-mccdaq/start

https://digilent.com/shop/mcc-usb-1608g-series-high-speed-multifunction-usb-daq-devices/

https://github.com/lukingroup/pylabnet/wiki/2.-Devices

**Comment by kelwerks** [comment]
https://files.digilent.com/manuals/Mcculw_WebHelp/Users_Guide/Analog_Input_Boards/USB-1608G_Series.htm
