### ISSUE TITLE
Add docstrings to client classes

### ISSUE THREAD

**Issue by mkbhaskar** [lukingroup/pylabnet#53]
Client classes (dummy wrapper implementation) don't have docstrings - these are written for the low level functions. However, in practical operation of pylabnet one uses the client functions, so it is helpful to have the documentation available when using the client functions in an IDE. This should be a simple copy paste job, unless there is a more elegant solution that @cknaut knows about?

**Comment by cknaut** [comment]
Maybe this could work ?


```python
class X(object):
  """This class has a method foo()."""
  def foo(): pass

class Y(X):
  __doc__ = X.__doc__ + ' Also bar().'
  def bar(): pass
```

We could maybe try implementing this in the `ClientBase` and `ServerBase`.
(https://stackoverflow.com/questions/2025562/inherit-docstrings-in-python-class-inheritance)
