### ISSUE TITLE
Enable SSH based start of proxy server and pylabnet server launch

### ISSUE THREAD

**Issue by cknaut** [lukingroup/pylabnet#99]
This alternative non-GUI based workflow can be useful in cases where shared machines are used and a remote desktop connection can be annoying to establish with multiple users.

**Comment by mkbhaskar** [comment]
should be made more secure (not password based, but perhaps SSL key based)

**Comment by cknaut** [comment]
also needs to be debugged for modules using a dll (wavemeter, mcs2)

**Comment by mkbhaskar** [comment]
not many good solutions, SSH doesn't work. need to consider something like this: https://pypi.org/project/pypsexec/

**Comment by cknaut** [comment]
Hint regarding failure of SSH based execution of DLLs: Starting the MCS2 server, which is also using a DLL works via SSH. So there should not be an intrinsic problem. 

Also asked a question at stackoverflow: https://stackoverflow.com/questions/65427665/python-executing-dll-based-functions-via-ssh-using-paramiko-and-ctypes
